import "~/styles/globals.css";

import { type Metadata } from "next";
import { Providers } from "~/app/providers";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Webová fakturační aplikace",
  description: "Generated by V0",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="cs">
      <body>
        <TRPCReactProvider>
          <Providers>
            {children}
          </Providers>
        </TRPCReactProvider>
      </body>
    </html>
  )
}
